### ISSUE TITLE
Wallet Address Link should redirect to the Shardeum Explorer

### ISSUE THREAD

**Issue by iSumitBanik** [naresh-golla/shardeum-nft#1]
**Overview**

The link for checking the details of a wallet address is currently redirecting the user to PolygonScan. It Should redirect to the Shardeum Explorer Page.

![image](https://user-images.githubusercontent.com/36637433/166155068-8b33bc51-cfa9-4ecb-9562-9731af0a760a.png)

**Comment by naresh-golla** [comment]
fixed in latest commit

**Comment by iSumitBanik** [comment]
Looks Good. Thanks.
